#!/bin/bash

set -euxo pipefail

TOP_DIR=$( cd `dirname "$0"` && /bin/pwd )

cd "${TOP_DIR}"/src/sqlite
INSTALL_DIR="${TOP_DIR}"/"$(git rev-parse --abbrev-ref HEAD)"

export CFLAGS="-O2 -fno-strict-aliasing -DSQLITE_SECURE_DELETE -DSQLITE_ENABLE_COLUMN_METADATA -DSQLITE_ENABLE_FTS3 -DSQLITE_ENABLE_FTS3_PARENTHESIS -DSQLITE_ENABLE_RTREE=1 -DSQLITE_SOUNDEX=1 -DSQLITE_ENABLE_UNLOCK_NOTIFY -DSQLITE_OMIT_LOOKASIDE=1 -DSQLITE_ENABLE_DBSTAT_VTAB -DSQLITE_ENABLE_UPDATE_DELETE_LIMIT=1 -DSQLITE_ENABLE_LOAD_EXTENSION -DSQLITE_ENABLE_JSON1 -DSQLITE_LIKE_DOESNT_MATCH_BLOBS -DSQLITE_THREADSAFE=0 -DSQLITE_ENABLE_FTS3_TOKENIZER=1 -DSQLITE_USE_URI=1 -DSQLITE_MAX_SCHEMA_RETRY=25 -DSQLITE_ENABLE_PREUPDATE_HOOK -DSQLITE_ENABLE_SESSION -DSQLITE_ENABLE_STMTVTAB -DSQLITE_MAX_VARIABLE_NUMBER=250000 -DSQLITE_MAX_DEFAULT_PAGE_SIZE=32768 -DSQLITE_DEFAULT_SYNCHRONOUS=0 -DUSE_PREAD64 -DSQLITE_DEFAULT_LOCKING_MODE=1 -DSQLITE_DEFAULT_MEMSTATUS=0   -DSQLITE_MAX_EXPR_DEPTH=0 -DSQLITE_OMIT_DEPRECATED -DSQLITE_OMIT_PROGRESS_CALLBACK -DSQLITE_OMIT_SHARED_CACHE -DSQLITE_USE_ALLOCA"

### This goes 1% faster at the cost of a lot of RAM
### -DSQLITE_DEFAULT_CACHE_SIZE=4194304

./configure --prefix="${INSTALL_DIR}" \
    --disable-threadsafe \
    --enable-json1 \
    --enable-fts4 \
    --enable-fts5 \
    --enable-tempstore=yes \
    --disable-tcl

make -j$(nproc)
make install
make clean
